### ISSUE TITLE
When the Scoreboard is started before the ctf it never loads (the Watcher exits)

### ISSUE THREAD

**Issue by Savallator** [enowars/bambi-scoreboard#22]
This is a stack trace i got when just starting the scoreboard and then the ctf. It will then never load any data:
```
scoreboard_watch_1  | parsing /data/scoreboard.json
scoreboard_watch_1  | Traceback (most recent call last):
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
scoreboard_watch_1  |     return _run_code(code, main_globals, None,
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
scoreboard_watch_1  |     exec(code, run_globals)
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 127, in <module>
scoreboard_watch_1  |     asyncio.run(main())
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
scoreboard_watch_1  |     return loop.run_until_complete(main)
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
scoreboard_watch_1  |     return future.result()
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 34, in main
scoreboard_watch_1  |     await parse_base_scoreboard(base_path)
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 74, in parse_base_scoreboard
scoreboard_watch_1  |     await parse_scoreboard(base_path)
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 96, in parse_scoreboard
scoreboard_watch_1  |     sb = JsonScoreboard(**obj)
scoreboard_watch_1  |   File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
scoreboard_watch_1  | pydantic.error_wrappers.ValidationError: 31 validation errors for JsonScoreboard
scoreboard_watch_1  | Services
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 0 -> TeamId
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 0 -> TotalPoints
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 0 -> AttackPoints
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 0 -> LostDefensePoints
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 0 -> ServiceLevelAgreementPoints
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 0 -> ServiceDetails
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 1 -> TeamId
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 1 -> TotalPoints
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 1 -> AttackPoints
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 1 -> LostDefensePoints
scoreboard_watch_1  |   field required (type=value_error.missing)
scoreboard_watch_1  | Teams -> 1 -> ServiceLevelAgreementPoints
scoreboard_watch_1  |   field required (type=value_error.missing)
```

**Comment by Savallator** [comment]
Never mind, it was an error in the engine...
