### ISSUE TITLE
RestartedException leads to another exception

### ISSUE THREAD

**Issue by ldruschk** [enowars/bambi-scoreboard#26]
```
scoreboard_watch_1  | Traceback (most recent call last):
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 76, in parse_base_scoreboard
scoreboard_watch_1  |     await parse_scoreboard(base_path)
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 118, in parse_scoreboard
scoreboard_watch_1  |     raise RestartedException()
scoreboard_watch_1  | __main__.RestartedException
scoreboard_watch_1  | 
scoreboard_watch_1  | During handling of the above exception, another exception occurred:
scoreboard_watch_1  | 
scoreboard_watch_1  | Traceback (most recent call last):
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
scoreboard_watch_1  |     return _run_code(code, main_globals, None,
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
scoreboard_watch_1  |     exec(code, run_globals)
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 129, in <module>
scoreboard_watch_1  |     asyncio.run(main())
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
scoreboard_watch_1  |     return loop.run_until_complete(main)
scoreboard_watch_1  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
scoreboard_watch_1  |     return future.result()
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 34, in main
scoreboard_watch_1  |     await parse_base_scoreboard(base_path)
scoreboard_watch_1  |   File "/service/scoreboard/watch.py", line 80, in parse_base_scoreboard
scoreboard_watch_1  |     await parse_ctf(CTF_JSON_PATH)
scoreboard_watch_1  | NameError: name 'parse_ctf' is not defined

```
I believe parse_ctf should be replaced with parse_info

**Comment by ldruschk** [comment]
@Savallator I believe that had to do with replacing the `ctf.json` with `ScoreboardInfo.json`
